config/routes.rb
TheCarryProject::Application.routes.draw do
  default_url_options host: Rails.application.config.domain
  resources :users
  resources :user_reviews
  resources :phones
  resources :sessions, only: [:new, :create, :destroy]
  resources :request_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    put :take, on: :member
    resources :comments
  end
  resources :suggest_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    resources :comments
  end
  resources :password_resets
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/privacy_policy',    to: 'static_pages#privacy_policy'
  match '/terms_of_use',    to: 'static_pages#terms_of_use'
  match '/faq',    to: 'static_pages#faq'

  match '/request', to:'request_deliveries#new'
  match '/giveaways', to:'request_deliveries#index_takers'
  match '/pickups', to:'request_deliveries#index_transporters'

  match '/get_the_item/:request_delivery_id', to:'request_deliveries#get_the_item', as: 'get_the_item'
  match '/got_the_item/:request_delivery_id', to:'request_deliveries#got_the_item', as: 'got_the_item'
  match '/another/:request_delivery_id', to:'request_deliveries#another_taker', as: 'another'
  match '/edit_request_cost/:request_delivery_id', to:'request_deliveries#edit_cost', as:'edit_request_cost'
  match '/edit_request_what/:request_delivery_id', to:'request_deliveries#edit_what', as:'edit_request_what'
  match '/edit_request_picture/:request_delivery_id', to:'request_deliveries#edit_picture', as:'edit_request_picture'
  match '/edit_request_from/:request_delivery_id', to:'request_deliveries#edit_from', as:'edit_request_from'
  match '/edit_request_delivery/:request_delivery_id', to:'request_deliveries#edit_delivery', as:'edit_request_delivery'
  match '/edit_request_to/:request_delivery_id', to:'request_deliveries#edit_to', as:'edit_request_to'
  match '/edit_request_size/:request_delivery_id', to:'request_deliveries#edit_size', as:'edit_request_size'
  match '/edit_request_due_date/:request_delivery_id', to:'request_deliveries#edit_due_date', as:'edit_request_due_date'
  match '/edit_sending_person/:request_delivery_id', to:'request_deliveries#edit_sending_person', as:'edit_sending_person'
  match '/edit_receiving_person/:request_delivery_id', to:'request_deliveries#edit_receiving_person', as:'edit_receiving_person'

  match '/pre_confirm_request/:accepted_request_id', to: 'request_deliveries#pre_confirm', as:'pre_confirm_request'
  match '/confirm_request', to:'request_deliveries#confirm'
  match '/pre_cancel_request/:accepted_request_id', to: 'request_deliveries#pre_cancel', as:'pre_cancel_request'
  match '/pre_complete_request/:accepted_request_id', to: 'request_deliveries#pre_complete', as:'pre_complete_request'
  match '/complete_request', to:'request_deliveries#complete'

  match '/suggest', to:'suggest_deliveries#new'
  match '/suggestions', to:'suggest_deliveries#index'

  match '/edit_suggest_cost/:suggest_delivery_id', to:'suggest_deliveries#edit_cost', as:'edit_suggest_cost'
  match '/edit_suggest_from/:suggest_delivery_id', to:'suggest_deliveries#edit_from', as:'edit_suggest_from'
  match '/edit_suggest_to/:suggest_delivery_id', to:'suggest_deliveries#edit_to', as:'edit_suggest_to'
  match '/edit_suggest_due_date/:suggest_delivery_id', to:'suggest_deliveries#edit_due_date', as:'edit_suggest_due_date'
  match '/edit_freq/:suggest_delivery_id', to:'suggest_deliveries#edit_freq', as:'edit_freq'

  match '/pre_authorize_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_authorize', as:'pre_authorize_suggest'
  match '/confirm_suggestion', to:'suggest_deliveries#confirm'
  match '/authorize_suggestion', to:'suggest_deliveries#authorize'
  match '/pre_cancel_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_cancel', as:'pre_cancel_suggest'
  match '/pre_complete_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_complete', as:'pre_complete_suggest'
  match '/complete_suggestion', to:'suggest_deliveries#complete'

  match '/activity', to:'activities#index'

  match '/verify/:id', to: 'users#verify', as:'verify'
  match '/confirm/:token', to: 'confirmations#confirm', as: 'confirm'

  match '/phone', to: 'phones#new'
  match '/send_code/:user_id', to: 'phones#send_code', as: 'send_code'
  match '/pre_verify_request/:request_delivery_id/:coming_from', to: 'phones#pre_verify_request', as: 'pre_verify_request'
  match '/pre_verify_suggest/:suggest_delivery_id/:coming_from', to: 'phones#pre_verify_suggest', as: 'pre_verify_suggest'
  match '/phone_verify/:user_id', to: 'phones#verify', as:'phone_verify'
  match '/phone_check', to: 'phone_verifications#phone_check'

  match '/reset_password', to: 'password_resets#new'
  match '/admin_reset/:user_id', to: 'password_resets#admin_reset', as:'admin_reset'

  match "empty_trash" => "users#empty_trash"

  match '/review/:request_delivery_id', to: 'user_reviews#new', as:'review'

  match '/auth/new' => 'authentications#new'
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => "authentications#failure" #OMNIAUTH
  match "facebook/logout", :to => "authentications#logout", :as => :logout_authentication

  get 'payments', to: 'payments#home', as: :home
  get 'payments/checkout', to: 'payments#checkout', as: :checkout
  get 'payments/cancel', to: 'payments#cancel', as: :cancel
  get 'payments/execute', to: 'payments#execute', as: :execute
  get 'payments/fail', to: 'payments#fail', as: :fail
  post 'payments/ipn_notification', to: 'payments#ipn_notification', as: :ipn_notification
  match '/details/:accepted_task_id/:req_or_sugg', to: 'payments#details', as: 'details'

end

app/views/shared/_maps.html.erb
<% if controller.controller_name == 'request_deliveries' && controller.action_name == 'show' %>
    <% if @request_delivery.to.present? && !@non_involved_user %>
        <%= render 'shared/route' %>
    <% else  %>
        <%= render 'shared/location' %>
    <% end  %>
<% end  %>

app/views/shared/_missing.html.erb
<div class="missing_detail">
  <div class="bubbleInfo">
    <%= image_tag("missing_detail.png", class: "trigger") %>
    <div class="popup" style="height:45px; width:280px; margin-top:33px;text-align: center;">
      Add all details to get priority in our lists.<br>
      Go to<b style="color:#ff9054"> Edit </b><%= image_tag("../assets/edit_post.png") %> and add this detail.
      <div id="tail1" style="left:33px"></div>
      <div id="tail2" style="left:33px"></div>
    </div>
  </div>
</div>

app/views/shared/_request_delivery_form.html.erb
<div class="new_delivery_request_class">
  <%= form_for(@request_delivery, :validate => true ) do |f| %>
      <fieldset>
        <div class="single_step">
          <legend  style="background-image: url('../assets/1.png');"><b>Origin</b></legend>
          <%= f.label :from, "Where do you want to deliver from?" %>
          <%= f.text_field :from, :placeholder => "Type origin address...", :class => "address_field" %>
          <%= f.label :sending_person, "Who is giving the package away?" %>
          <%= f.text_field :sending_person, :value => "#{@request_delivery.user.name}" %>
        </div>
      </fieldset>
      <fieldset>
        <div class="single_step">
          <legend  style="background-image: url('../assets/2.png');"><b>Destination</b></legend>
          <%= f.label :to, "Where do you want your delivery to reach?" %>
          <%= f.text_field :to, :placeholder => "Type destination address...", :class => "address_field"   %>
          <%= f.label :receiving_person, "Who is accepting the package in the end?" %>
          <%= f.text_field :receiving_person, :value => "#{@request_delivery.user.name}" %>
        </div>
      </fieldset>
      <fieldset>
        <div class="single_step">
          <legend  style="background-image: url('../assets/3.png');"><b>Delivery Contents</b></legend>
          <%= f.label :what, "What is it that you want to deliver?" %>
          <%= f.text_field :what, :placeholder => "Type delivery contents..."   %>
          <%= f.label :size, "How big is your delivery?" %>
          <div class="radio_buttons">
            <div class="radio_button" style="text-align:left">
              <%= f.radio_button(:size, "Small") %>
              <%= f.label(:size_small, "Small") %>
            </div>
            <div class="radio_button" style="text-align:left">
              <%= f.radio_button(:size, "Medium") %>
              <%= f.label(:size_small, "Medium") %>
            </div>
            <div class="radio_button" style="text-align:left">
              <%= f.radio_button(:size, "Large") %>
              <%= f.label(:size_small, "Large") %>
            </div>
          </div>
          <%= f.label :more_details, "Please provide some more details:" %>
          <%= f.text_area :more_details, :placeholder => "Add any detail that might be important...", :rows => 2 %>
        </div>
      </fieldset>
      <fieldset>
        <div class="single_step">
          <legend  style="background-image: url('../assets/4.png');"><b>Time of Delivery</b></legend>
          <%= f.label :when, "When would you like your delivery to ship?" %>
          <%= f.text_field :when, :placeholder => "mm/dd/yyyy", :class => "datepicker" %>
        </div>
      </fieldset>
      <fieldset>
        <div class="single_step">
          <legend  style="background-image: url('../assets/5.png');"><b>Payment</b></legend>
          <%= f.label :cost, "How much will you pay for the delivery?" %>
          <%= f.text_field :cost, :placeholder => "Type an amount in NIS..."   %>
          <div class="form_submit">
            <%= f.submit "Finish", :type => :image, :src => "assets/Finish.png", :class => "finish" %>
          </div>
        </div>
      </fieldset>
  <% end  %>
</div>


app/views/shared/_request_feed_pick_ups_item.html.erb
<div class="feed_item" onclick="location.href='<%=request_delivery_path(request_feed_pick_ups_item)%>'">
  <% if (current_user.try(:admin?)) %>
      <div class="delete_post">
        <div class="bubbleInfo">
          <%=  link_to image_tag("delete_post.png"), request_feed_pick_ups_item, method: :delete, class: "trigger" %>
          <div class="popup" style="height:20px; width:165px; margin-top:57px;">
            <b style="color:#FF0523;">Delete</b> delivery request.
            <div id="tail1" style="left:37px"></div>
            <div id="tail2" style="left:37px"></div>
          </div>
        </div>
      </div>
      <% if request_feed_pick_ups_item.has_all_details %>
          <div class="has_all_details">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="text-align:center;height:17px; width:285px; margin-top:60px;">
                This Pick up has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% elsif current_user.nil? || current_user.present? && request_feed_pick_ups_item.user != current_user %>
      <% if request_feed_pick_ups_item.has_all_details %>
          <div class="has_all_details" style="right:3px">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="text-align:center;height:17px; width:285px; margin-top:60px;">
                This Pick up has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% elsif request_feed_pick_ups_item.user == current_user %>
      <% if request_feed_pick_ups_item.has_all_details %>
          <div class="has_all_details" style="right:3px;">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="text-align:center;height:17px; width:285px; margin-top:60px;">
                Your Pick up has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% end %>
  <div class="feed_item_info">
    <div class="feed_title" onclick="location.href='<%=request_delivery_path(request_feed_pick_ups_item)%>'">
      <b><%= link_to request_feed_pick_ups_item.what, request_delivery_path(request_feed_pick_ups_item)  %></b>
    </div>
    <div class="feed_request_data">
      <% if request_feed_pick_ups_item.attachment.present? %>
        <div class="feed_item_money" style="bottom:186px;left:36px;">
        <%= request_feed_pick_ups_item.cost %> <%= request_feed_pick_ups_item.currency %>
      </div>
      <% else  %>
            <div class="feed_item_money">
            <%= request_feed_pick_ups_item.cost %> <%= request_feed_pick_ups_item.currency %>
          </div>
      <% end  %>
      <b>From</b> <%= request_feed_pick_ups_item.from %><br>
      <b>To</b> <%= request_feed_pick_ups_item.to %><br>
      <b>Size</b> <%= request_feed_pick_ups_item.size %><br>
      <b>Needed By</b> <%= link_to request_feed_pick_ups_item.confirmed_taker.name, request_feed_pick_ups_item.confirmed_taker %><br>
      <% if request_feed_pick_ups_item.attachment.present? %>
          <div class="feed_item_thumb" onclick="location.href='<%=request_delivery_path(request_feed_pick_ups_item)%>'">
            <%= image_tag request_feed_pick_ups_item.attachment_url(:thumb).to_s  %>
          </div>
      <% else  %>
          <div class="feed_item_map" onclick="location.href='<%=request_delivery_path(request_feed_pick_ups_item)%>'">
            <img src="http://maps.google.com/maps/api/staticmap?size=250x180&maptype=roadmap&sensor=false&markers=color:green|label:A|<%= request_feed_pick_ups_item.from %>&markers=color:red|label:B|<%= request_feed_pick_ups_item.to %>"></img>
          </div>
      <% end  %>
    </div>
  </div>
</div>

app/views/shared/_request_feed_takers.html.erb
<div class="search_posts">
  <div class="search_title">
    <b>Giveaways</b>
  </div>
  <%= form_for @search, :url => giveaways_path, :html => {:method => :get} do |f| %>
      <div class="search_fields">
        <div class="myfield_search">
          <%= f.label :from_contains, "I'm looking for stuff from" %>
          <%= f.text_field :from_contains, :class => "address_field" %>
          <%=  f.submit "Filter" , :id => 'submit_filter'%>
        </div>
      </div>
  <% end %>
</div>
<div class="requestposts">
  <% if @request_feed_items.any? %>
      <%= render partial: 'shared/request_feed_takers_item', collection: @request_feed_items %>
  <% else  %>
      <h3><center>No Giveaways available at the moment!</center></h3>
  <% end  %>
</div>

app/views/shared/_request_feed_takers_item.html.erb
<div class="feed_item" onclick="location.href='<%=request_delivery_path(request_feed_takers_item)%>'">
  <% if (current_user.try(:admin?)) %>
      <div class="delete_post">
        <div class="bubbleInfo">
          <%=  link_to image_tag("delete_post.png"), request_feed_takers_item, method: :delete, class: "trigger" %>
          <div class="popup" style="height:20px; width:165px; margin-top:57px;">
            <b style="color:#FF0523;">Delete</b> delivery request.
            <div id="tail1" style="left:37px"></div>
            <div id="tail2" style="left:37px"></div>
          </div>
        </div>
      </div>
      <% if request_feed_takers_item.has_all_details %>
          <div class="has_all_details">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="height:20px; width:315px; margin-top:57px;">
                This Giveaway has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% elsif current_user.nil? || current_user.present? && request_feed_takers_item.user != current_user %>
      <% if request_feed_takers_item.has_all_details %>
          <div class="has_all_details" style="right:3px">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="height:20px; width:315px; margin-top:57px;">
                This Giveaway has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% elsif request_feed_takers_item.user == current_user %>
      <% if request_feed_takers_item.has_all_details %>
          <div class="has_all_details" style="right:3px;">
            <div class="bubbleInfo">
              <%= image_tag("has_all_details.png", class: "trigger") %>
              <div class="popup" style="height:20px; width:315px; margin-top:57px;">
                Your Giveaway has <b style="color:#279227">all</b> the necessary details!
                <div id="tail1" style="left:35px"></div>
                <div id="tail2" style="left:35px"></div>
              </div>
            </div>
          </div>
      <% end  %>
  <% end %>
  <div class="feed_item_info">
    <% if request_feed_takers_item.attachment.present? %>
        <div class="feed_item_thumb" onclick="location.href='<%=request_delivery_path(request_feed_takers_item)%>'">
          <%= image_tag request_feed_takers_item.attachment_url(:thumb).to_s  %>
        </div>
    <% else  %>
        <div class="feed_item_map" onclick="location.href='<%=request_delivery_path(request_feed_takers_item)%>'">
          <img src="http://maps.google.com/maps/api/staticmap?size=210x180&maptype=roadmap&sensor=false&markers=color:green|label:A|<%= request_feed_takers_item.from %>&markers=color:red|label:B|<%= request_feed_takers_item.to %>"></img>
        </div>
    <% end  %>
    <div class="feed_title" onclick="location.href='<%=request_delivery_path(request_feed_takers_item)%>'">
      <b><%= request_feed_takers_item.what %></b>
    </div>
    <div class="feed_mini_title">
      <%= request_feed_takers_item.from %>
    </div>
  </div>
</div>

app/views/shared/_suggest_feed.html.erb
<div class="search_posts">
  <div class="search_title">
    <b>Delivery Suggestions</b>
  </div>
  <%= form_for @search, :url => suggestions_path, :html => {:method => :get} do |f| %>
      <div class="search_fields">
        <div class="myfield_search">
          <%= f.label :from_contains, "From" %>
          <%= f.text_field :from_contains, :class => "address_field" %>
          <%= f.label :to_contains, "To" %>
          <%= f.text_field :to_contains, :class => "address_field" %>
          <%=  f.submit "Filter" , :id => 'submit_filter'%>
        </div>
      </div>
  <% end %>
</div>
<div class="add_your_own">
  <div class="send_button_index"  onclick="location.href='/request'">
    <b>Ask for a pick up.</b>
  </div>
</div>
<div class="suggestposts">
  <% if @suggest_feed_items.any? %>
      <%= render partial: 'shared/suggest_feed_item', collection: @suggest_feed_items %>
  <% else  %>
      <h3>No delivery suggestions available at the moment!</h3>
  <% end  %>
</div>

app/views/shared/_suggest_feed_item.html.erb
<% if suggest_feed_item.status == "Open" || suggest_feed_item.status == "Pending Confirmation" %>
    <div class="feed_item" onclick="location.href='<%=suggest_delivery_path(suggest_feed_item)%>'">
      <% if (current_user.try(:admin?)) %>
          <div class="delete_post">
            <div class="bubbleInfo">
              <%=  link_to image_tag("delete_post.png"), suggest_feed_item, method: :delete, class: "trigger" %>
              <div class="popup" style="height:20px; width:220px; margin-top:57px;">
                <b style="color:#FF0523;">Delete</b> delivery suggestion.
                <div id="tail1" style="left:37px"></div>
                <div id="tail2" style="left:37px"></div>
              </div>
            </div>
          </div>
          <% if suggest_feed_item.has_all_details %>
              <div class="has_all_details">
                <div class="bubbleInfo">
                  <%= image_tag("has_all_details.png", class: "trigger") %>
                  <div class="popup" style="height:20px; width:305px; margin-top:57px;">
                    This suggestion has <b style="color:#279227">all</b> the necessary details!
                    <div id="tail1" style="left:35px"></div>
                    <div id="tail2" style="left:35px"></div>
                  </div>
                </div>
              </div>
          <% end %>
      <% elsif current_user.nil? || current_user.present? && suggest_feed_item.user != current_user %>
          <% if suggest_feed_item.has_all_details %>
              <div class="has_all_details" style="right:3px">
                <div class="bubbleInfo">
                  <%= image_tag("has_all_details.png", class: "trigger") %>
                  <div class="popup" style="height:20px; width:305px; margin-top:57px;">
                    This suggestion has <b style="color:#279227">all</b> the necessary details!
                    <div id="tail1" style="left:35px"></div>
                    <div id="tail2" style="left:35px"></div>
                  </div>
                </div>
              </div>
          <% end %>
      <% elsif suggest_feed_item.user == current_user %>
          <% if suggest_feed_item.has_all_details %>
              <div class="has_all_details" style="right:3px;">
                <div class="bubbleInfo">
                  <%= image_tag("has_all_details.png", class: "trigger") %>
                  <div class="popup" style="height:20px; width:305px; margin-top:57px;">
                    Your suggestion has <b style="color:#279227">all</b> the necessary details!
                    <div id="tail1" style="left:35px"></div>
                    <div id="tail2" style="left:35px"></div>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
      <div class="feed_item_info">
        <div class="feed_title" onclick="location.href='<%=suggest_delivery_path(suggest_feed_item)%>'">
          <b><%= link_to suggest_feed_item.size+" sized items", suggest_delivery_path(suggest_feed_item)  %></b>
        </div>
        <div class="feed_item_money">
          <%= suggest_feed_item.cost %> <%= suggest_feed_item.currency %>
        </div>
        <div class="feed_request_data">
          <b>From</b> <%= suggest_feed_item.from %><br>
          <b>To</b> <%= suggest_feed_item.to %><br>
          <b>By</b> <%= link_to suggest_feed_item.user.name, suggest_feed_item.user %><br>
          <% if suggest_feed_item.user.transporter_reviews.any? %>
              <% @user = suggest_feed_item.user %><%=render 'shared/transporter_star_rating_small' %>
              (<%= suggest_feed_item.user.transporter_reviews.count %>)
          <% else  %>
              Transporter not rated yet
          <% end  %>
          <div class="feed_item_map" onclick="location.href='<%=suggest_delivery_path(suggest_feed_item)%>'">
            <img src="http://maps.google.com/maps/api/staticmap?size=250x180&maptype=roadmap&sensor=false&markers=color:red|label:A|<%= suggest_feed_item.from %>&markers=color:red|label:B|<%= suggest_feed_item.to %>"></img>
          </div>
        </div>
      </div>
    </div>
<% end  %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name  %>
</h1>
<span>
  <%= link_to "View my profile", current_user  %>
</span>

app/views/shared/_wizards.html.erb
 <% if controller.controller_name == 'request_deliveries' && controller.action_name == 'new' %>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#new_request_delivery").mapsAndDate()
        });
    </script>
 <% elsif controller.controller_name == 'request_deliveries' && controller.action_name == 'edit_from' %>
     <script type="text/javascript">
         $(document).ready(function(){
             $("#edit_from").mapsAndDate()
         });
     </script>
     <% elsif controller.controller_name == 'request_deliveries' && controller.action_name == 'edit_to' %>
         <script type="text/javascript">
             $(document).ready(function(){
                 $("#edit_to").mapsAndDate()
             });
         </script>
 <% elsif controller.controller_name == 'request_deliveries' && controller.action_name == 'index_takers' %>
     <script type="text/javascript">
         $(document).ready(function(){
             $("#request_delivery_search").mapsAndDate()
         });
     </script>
<% elsif controller.controller_name == 'suggest_deliveries' && controller.action_name == 'new' %>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#new_suggest_delivery").mapsAndDate()
        });
    </script>
 <% elsif controller.controller_name == 'suggest_deliveries' && controller.action_name == 'edit_from' %>
     <script type="text/javascript">
         $(document).ready(function(){
             $("#edit_from").mapsAndDate()
         });
     </script>
 <% elsif controller.controller_name == 'suggest_deliveries' && controller.action_name == 'edit_to' %>
     <script type="text/javascript">
         $(document).ready(function(){
             $("#edit_to").mapsAndDate()
         });
     </script>
 <% elsif controller.controller_name == 'suggest_deliveries' && controller.action_name == 'index' %>
     <script type="text/javascript">
         $(document).ready(function(){
             $("#suggest_delivery_search").mapsAndDate()
         });
     </script>
<% end %>