config/routes.rb
TheCarryProject::Application.routes.draw do
  default_url_options host: Rails.application.config.domain
  resources :users
  resources :user_reviews
  resources :phones
  resources :sessions, only: [:new, :create, :destroy]
  resources :request_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    put :take, on: :member
    resources :comments
  end
  resources :suggest_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    resources :comments
  end
  resources :password_resets
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/privacy_policy',    to: 'static_pages#privacy_policy'
  match '/terms_of_use',    to: 'static_pages#terms_of_use'
  match '/faq',    to: 'static_pages#faq'

  match '/request', to:'request_deliveries#new'
  match '/giveaways', to:'request_deliveries#index_takers'
  match '/pickups', to:'request_deliveries#index_transporters'

  match '/get_the_item/:request_delivery_id', to:'request_deliveries#get_the_item', as: 'get_the_item'
  match '/got_the_item/:request_delivery_id', to:'request_deliveries#got_the_item', as: 'got_the_item'
  match '/another/:request_delivery_id', to:'request_deliveries#another_taker', as: 'another'
  match '/edit_request_cost/:request_delivery_id', to:'request_deliveries#edit_cost', as:'edit_request_cost'
  match '/edit_request_what/:request_delivery_id', to:'request_deliveries#edit_what', as:'edit_request_what'
  match '/edit_request_picture/:request_delivery_id', to:'request_deliveries#edit_picture', as:'edit_request_picture'
  match '/edit_request_from/:request_delivery_id', to:'request_deliveries#edit_from', as:'edit_request_from'
  match '/edit_request_delivery/:request_delivery_id', to:'request_deliveries#edit_delivery', as:'edit_request_delivery'
  match '/edit_request_to/:request_delivery_id', to:'request_deliveries#edit_to', as:'edit_request_to'
  match '/edit_request_size/:request_delivery_id', to:'request_deliveries#edit_size', as:'edit_request_size'
  match '/edit_request_due_date/:request_delivery_id', to:'request_deliveries#edit_due_date', as:'edit_request_due_date'
  match '/edit_sending_person/:request_delivery_id', to:'request_deliveries#edit_sending_person', as:'edit_sending_person'
  match '/edit_receiving_person/:request_delivery_id', to:'request_deliveries#edit_receiving_person', as:'edit_receiving_person'

  match '/pre_confirm_request/:accepted_request_id', to: 'request_deliveries#pre_confirm', as:'pre_confirm_request'
  match '/confirm_request', to:'request_deliveries#confirm'
  match '/pre_cancel_request/:accepted_request_id', to: 'request_deliveries#pre_cancel', as:'pre_cancel_request'
  match '/pre_complete_request/:accepted_request_id', to: 'request_deliveries#pre_complete', as:'pre_complete_request'
  match '/complete_request', to:'request_deliveries#complete'

  match '/suggest', to:'suggest_deliveries#new'
  match '/suggestions', to:'suggest_deliveries#index'

  match '/edit_suggest_cost/:suggest_delivery_id', to:'suggest_deliveries#edit_cost', as:'edit_suggest_cost'
  match '/edit_suggest_from/:suggest_delivery_id', to:'suggest_deliveries#edit_from', as:'edit_suggest_from'
  match '/edit_suggest_to/:suggest_delivery_id', to:'suggest_deliveries#edit_to', as:'edit_suggest_to'
  match '/edit_suggest_due_date/:suggest_delivery_id', to:'suggest_deliveries#edit_due_date', as:'edit_suggest_due_date'
  match '/edit_freq/:suggest_delivery_id', to:'suggest_deliveries#edit_freq', as:'edit_freq'

  match '/pre_authorize_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_authorize', as:'pre_authorize_suggest'
  match '/confirm_suggestion', to:'suggest_deliveries#confirm'
  match '/authorize_suggestion', to:'suggest_deliveries#authorize'
  match '/pre_cancel_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_cancel', as:'pre_cancel_suggest'
  match '/pre_complete_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_complete', as:'pre_complete_suggest'
  match '/complete_suggestion', to:'suggest_deliveries#complete'

  match '/activity', to:'activities#index'

  match '/verify/:id', to: 'users#verify', as:'verify'
  match '/confirm/:token', to: 'confirmations#confirm', as: 'confirm'

  match '/phone', to: 'phones#new'
  match '/send_code/:user_id', to: 'phones#send_code', as: 'send_code'
  match '/pre_verify_request/:request_delivery_id/:coming_from', to: 'phones#pre_verify_request', as: 'pre_verify_request'
  match '/pre_verify_suggest/:suggest_delivery_id/:coming_from', to: 'phones#pre_verify_suggest', as: 'pre_verify_suggest'
  match '/phone_verify/:user_id', to: 'phones#verify', as:'phone_verify'
  match '/phone_check', to: 'phone_verifications#phone_check'

  match '/reset_password', to: 'password_resets#new'
  match '/admin_reset/:user_id', to: 'password_resets#admin_reset', as:'admin_reset'

  match "empty_trash" => "users#empty_trash"

  match '/review/:request_delivery_id', to: 'user_reviews#new', as:'review'

  match '/auth/new' => 'authentications#new'
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => "authentications#failure" #OMNIAUTH
  match "facebook/logout", :to => "authentications#logout", :as => :logout_authentication

  get 'payments', to: 'payments#home', as: :home
  get 'payments/checkout', to: 'payments#checkout', as: :checkout
  get 'payments/cancel', to: 'payments#cancel', as: :cancel
  get 'payments/execute', to: 'payments#execute', as: :execute
  get 'payments/fail', to: 'payments#fail', as: :fail
  post 'payments/ipn_notification', to: 'payments#ipn_notification', as: :ipn_notification
  match '/details/:accepted_task_id/:req_or_sugg', to: 'payments#details', as: 'details'

end

app/controllers/request_deliveries_controller.rb
class RequestDeliveriesController < ApplicationController
  before_filter :signed_in_user, :except => [:show, :index_takers, :index_transporters, :new, :create]
  before_filter :correct_user,   only: [:destroy, :update]
  respond_to :html, :js

  def show
    @request_delivery = RequestDelivery.find(params[:id])
    if @request_delivery.status != "Open" && @request_delivery.status != "Unpublished"
      @taking_user = @request_delivery.confirmed_taker
    end
    if current_user.nil?
      if @request_delivery.status != "Open" && @request_delivery.status != "WaitingForTransporter" && @request_delivery.status != "Pending Confirmation"
        @non_involved_user = true
      end
    else
      @my_taken_giveaway = TakenGiveaway.find_by_user_id_and_request_delivery_id(current_user.id,@request_delivery.id)
      @any_taken_giveaway = TakenGiveaway.find_by_request_delivery_id(@request_delivery.id)
      @accepted_request = AcceptedRequest.find_by_user_id_and_request_delivery_id(current_user.id,@request_delivery.id)
      @someone_is_confirmed = AcceptedRequest.find_by_request_delivery_id_and_confirmed(@request_delivery.id,true)
      if @someone_is_confirmed
        @transporter = @request_delivery.accepted_request_confirmed.other_user_for_request
      end
      @my_phone = Phone.find_by_user_id(current_user.id)

      @show_bounty = (@request_delivery.status == "WaitingForTransporter" ||
          @request_delivery.status == "Pending Confirmation" ||
          @request_delivery.status == "Confirmed" ||
          @request_delivery.status == "Complete" ||
          @request_delivery.status == "TransporterReviewed") &&
          @request_delivery.user != current_user &&
          @taking_user != current_user

      @non_editable = @request_delivery.status == "ReceiverConfirmed" ||
          @request_delivery.status == "WaitingForTransporter" ||
          @request_delivery.status == "Pending Confirmation" ||
          @request_delivery.status == "Confirmed" ||
          @request_delivery.status == "Complete" ||
          @request_delivery.status == "TransporterReviewed"

      @after_delivery = @request_delivery.status == "Complete" ||
          @request_delivery.status == "TransporterReviewed"

      @big_sender_receiver = @request_delivery.status == "ReceiverConfirmed" ||
          @request_delivery.status == "Confirmed"

      @my_giveaway_accepted = AcceptedRequest.find_all_by_request_delivery_id(@request_delivery.id)

      if @request_delivery.status != "Open" &&
          @request_delivery.status != "WaitingForTransporter" &&
          @request_delivery.status != "Pending Confirmation" &&
          @request_delivery.user != current_user &&
          @transporter != current_user &&
          @any_taken_giveaway.present? &&
          @any_taken_giveaway.taken &&
          @any_taken_giveaway.user_id != current_user.id
        @non_involved_user = true
      end
    end

    @facebook_authentication = Authentication.find_by_user_id(@request_delivery.user.id)

    @phone = Phone.find_by_user_id(@request_delivery.user.id)
    @commentable = @request_delivery
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    if current_user.nil?
      @request_delivery = RequestDelivery.new
    else
      @request_delivery = current_user.request_deliveries.build
    end
  end

  def create
    if current_user.nil?
      @request_delivery = RequestDelivery.new(params[:request_delivery])
      if @request_delivery.valid?
        session[:request_delivery_what] = @request_delivery.what
        session[:request_delivery_from] = @request_delivery.from
        session[:request_delivery_size] = @request_delivery.size
        session[:request_delivery_attachment] = @request_delivery.attachment
      end
    else
      @phone = Phone.find_by_user_id(current_user.id)
      @request_delivery = current_user.request_deliveries.build(params[:request_delivery])
      if @request_delivery.save
        @request_delivery.set_giver
        if @phone.present?
          @request_delivery.set_giver_phone
        end
        @request_delivery.publish
        flash[:success] = "Thank you!<br>
                                              <div class='sub_flash_text'>Your Giveaway was successfully added to our lists. <br>
                                              Perhaps some of your friends might be interested in it?<br><br>
                                             <a href=#{@request_delivery.facebook_share_giveaway_owner} target='_blank' class='facebook_share'>Share your Giveaway on Facebook!</a></div>".html_safe
        respond_with(@request_delivery) do |format|
          format.html { redirect_to request_delivery_url(@request_delivery)}
        end
      end
    end
  end

  def index_takers
    @open_requests = RequestDelivery.where("status = ?","Open")
    @search = @open_requests.search(params[:search])
    @request_feed_items = @search.all.sort_by { |a| a.has_all_details ? 0 : 1}
  end

  def index_transporters
    @transporter_requests = RequestDelivery.where("status = ? OR status = ?","WaitingForTransporter","Pending Confirmation")
    @search = @transporter_requests.search(params[:search])
    @request_feed_items = @search.all.sort_by { |a| a.has_all_details ? 0 : 1}
  end

  def edit_cost
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_cost.html.erb", :layout => false
    end
  end

  def edit_what
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_what.html.erb", :layout => "empty"
    end
  end

  def edit_picture
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_picture.html.erb", :layout => "empty"
    end
  end

  def edit_from
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_from.html.erb", :layout => "empty"
    end
  end

  def edit_delivery
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    @my_taken_giveaway = TakenGiveaway.find_by_user_id_and_request_delivery_id(current_user.id,@request_delivery.id)
    @taking_user = User.find_by_id(@my_taken_giveaway.user_id)
    if @taking_user == current_user
      render "edit_delivery.html.erb", :layout => "empty"
    end
  end

  def edit_to
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    @my_taken_giveaway = TakenGiveaway.find_by_user_id_and_request_delivery_id(current_user.id,@request_delivery.id)
    @taking_user = User.find_by_id(@my_taken_giveaway.user_id)
    if @taking_user == current_user
      render "edit_to.html.erb", :layout => "empty"
    end
  end

  def edit_size
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_size.html.erb", :layout => false
    end
  end

  def edit_due_date
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_due_date.html.erb", :layout => "empty"
    end
  end

  def edit_sending_person
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_sending_person.html.erb", :layout => false
    end
  end

  def edit_receiving_person
    @request_delivery = RequestDelivery.find(params[:request_delivery_id])
    if @request_delivery.user == current_user
      render "edit_receiving_person.html.erb", :layout => false
    end
  end

  def update
    @request_delivery = RequestDelivery.find(params[:id])
    @my_taken_giveaway = TakenGiveaway.find_by_user_id_and_request_delivery_id(current_user.id,@request_delivery.id)
    if @request_delivery.status == "Open" && @request_delivery.user != current_user
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>Only the owner of this giveaway can edit its details.</div>".html_safe
      redirect_to :back
    elsif @my_taken_giveaway.present? && @request_delivery.status == "Taken" && @my_taken_giveaway.user_id != current_user.id
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>Someone has decided to take this giveaway, so you cannot edit its details.</div>".html_safe
      redirect_to :back
    else
      @request_delivery.assign_attributes( params[:request_delivery])
      if @request_delivery.to_changed?
        @request_delivery.calculate_distance
        @request_delivery.set_cost
        @request_delivery.update_attribute(:delivery_type, nil)
      end
      if @request_delivery.update_attributes( params[:request_delivery])
        @request_delivery.check_all_details
        flash[:success] = "Thank you!<br><div class='sub_flash_text'>Your details were successfully updated.</div>".html_safe
        respond_with(@request_delivery) do |format|
          format.html { redirect_to request_delivery_url(@request_delivery)}
        end
      end
    end
  end

  def destroy
    @request_delivery = RequestDelivery.find(params[:id])
    if @request_delivery.status != "Open" && @request_delivery.status != "Unpublished"
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot delete your giveaway since someone has already accepted it.</div>".html_safe
      redirect_to :back
    else
      @request_delivery.destroy
      flash[:success] = "Thank you!<br><div class='sub_flash_text'>Your giveaway has been successfully deleted.</div>".html_safe
      redirect_to giveaways_path
    end
  end

  def take
    @request_delivery = RequestDelivery.find(params[:id])
    @phone = Phone.find_by_user_id(current_user.id)
    type = params[:type]
    if current_user != @request_delivery.user
      if type == "take" && @request_delivery.status == "Open"

app/views/request_deliveries/renders/_ar_taking_user.html.erb
<% if @request_delivery.status == "Taken" %>
    <% if @request_delivery.has_all_details %>
        <div class="ready_to_go_wrapper">
          <%=  link_to "Confirm Details",
                       {:controller => "request_deliveries",
                        :action => "get_the_item",
                        :request_delivery_id => @request_delivery.id},
                       :class =>"ready_to_go" %>
        </div>
    <% end  %>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Waiting for details
        <div class="giveaway_status_data">
          We're waiting for <b style="color:#f2ff5e">You</b> to add the missing details (<b style="color:#f2ff5e">To</b> and
          <b style="color:#f2ff5e"> Delivery Option</b>) and confirm.
        </div>
      </div>
    </div>
<% elsif @request_delivery.status == "ReceiverConfirmed" && @request_delivery.delivery_type == "myself" %>
    <div class="the_transporter">
      <div class="the_transporter_inner"  style="background-image: url('../assets/transporting_small.png');text-align:left">
        <div class="inner_title" style="padding-left: 55px;" >
          <b>Transporting</b>
        </div>
        <b>We have </b><b style="color:#f2ff5e">You</b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <b> (from <%= link_to @request_delivery.user.name, @request_delivery.user %>) and deliverying it to</b><b style="color:#f35044"> Point B</b>
        <b> (to </b><b style="color:#f2ff5e">You</b><b>).</b><br>
      </div>
    </div>
    <div class="ready_to_go_wrapper" style="margin-bottom: 20px;">
      <%=  link_to "OK, I got the item!",
                   {:controller => "request_deliveries",
                    :action => "got_the_item",
                    :request_delivery_id => @request_delivery.id},
                   :class =>"ok_got_it" %>
    </div>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Waiting for pick up
        <div class="giveaway_status_data">
          We're waiting for <b style="color:#f2ff5e">You</b> to go and pick up the item <b><%= link_to @request_delivery.user.name, @request_delivery.user %></b> is giving away.
        </div>
      </div>
    </div>
<% elsif @request_delivery.status == "WaitingForTransporter" && @taking_user == current_user %>
    <div class="ready_to_go_wrapper" style="margin-bottom: 10px;margin-top: 20px;">
      <a href="<%= @request_delivery.facebook_share_pick_up_owner %>" target="_blank" class="facebook_share">
        Find a Transporter - Share on Facebook
      </a>
    </div>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Locating Transporters
        <div class="giveaway_status_data">
          We're currently locating Transporters for your pick up.<br>
          Don't worry! We'll find some in no time.
        </div>
      </div>
    </div>
<% elsif @request_delivery.status == "Pending Confirmation" %>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Choose a Transporter
        <div class="giveaway_status_data">
          These Transporters are ready to go pick up your item! <br>
          In order to proceed, you must confirm one of them.
        </div>
      </div>
    </div>
    <% @my_giveaway_accepted.each do |acceptance| %>
        <div class="show_accepting_user_wrapper" style="margin-bottom: 20px;">
          <div class="show_accepting_user">
            <div class="confirm_transporter_wrapper">
              <% if @my_phone.present? && @my_phone.verified %>
                  <%=  link_to "Confirm Transporter", pre_confirm_request_path(acceptance.id), class:"confirm_transporter modal-link trigger",
                               "data-target" => "#myModal",
                               "data-toggle" => "modal",
                               "data-backdrop" => "static" %>
              <% else  %>
                  <%=  link_to "Confirm Transporter", pre_verify_request_path(acceptance.request_delivery_id,"confirm"), class:"confirm_transporter modal-link trigger",
                               "data-target" => "#myModal",
                               "data-toggle" => "modal",
                               "data-backdrop" => "static" %>
              <% end  %>
            </div>
            <div class="chat_gravatar" style="float:left; width:50px; text-align: center; margin-right: 8px;">
              <% if facebook_authorization(acceptance.other_user_for_request)  %>
                  <%= link_to facebook_profile_photo(acceptance.other_user_for_request,"chat"), acceptance.other_user_for_request %>
              <% else  %>
                  <%=  link_to chat_gravatar_for(acceptance.other_user_for_request), acceptance.other_user_for_request  %>
              <% end  %>
            </div>
            <b><%= link_to acceptance.other_user_for_request.name, acceptance.other_user_for_request  %></b>
            <% if acceptance.other_user_for_request.transporter_reviews.any? %>
                <div class="star_rating" style="margin-top:5px;margin-bottom:5px;">
                  <% @user = acceptance.other_user_for_request %>
                  <%=render 'shared/transporter_star_rating' %> (<%= acceptance.other_user_for_request.transporter_reviews.count %>)
                </div>
            <% else  %>
                <div class="not_yet_rated">
                  Transporter not rated yet
                </div>
            <% end  %>
          </div>
        </div>
    <% end  %>
<% elsif @request_delivery.status == "Confirmed" %>
    <div class="the_transporter">
      <div class="the_transporter_inner"  style="background-image: url('../assets/transporting_small.png');text-align:left">
        <div class="inner_title" style="padding-left: 55px;" >
          <b>Transporting</b>
        </div>
        <b>We have <%= link_to @transporter.name, @transporter  %></b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <b> (from <%= link_to @request_delivery.user.name, @request_delivery.user %>) and deliverying it to</b><b style="color:#f35044"> Point B</b>
        <b> (to </b><b style="color:#f2ff5e">You</b><b>).</b><br>
        <b style="color:#f2ff5e">You</b><b> can call him/her  at</b><b style="color:#f2ff5e"> <%= @transporter.phone %></b><b>.</b>
      </div>
    </div>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Transporter on the way
        <div class="giveaway_status_data">
          You've confirmed <%= link_to @transporter.name, @transporter %>
          to pick up your item. <br>
          Once the pick up is complete, the PayPal transaction you've authorized will take place.
        </div>
      </div>
    </div>
<% elsif @request_delivery.status == "Complete" %>
    <div class="the_transporter">
      <div class="the_transporter_inner"  style="background-image: url('../assets/transporting_small.png');text-align:left">
        <div class="inner_title" style="padding-left: 55px;" >
          <b>Transporting</b>
        </div>
        <% if @request_delivery.delivery_type == "myself" %>
            <b>We've had </b><b style="color:#f2ff5e">You</b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <% elsif @request_delivery.delivery_type == "senddme" %>
            <b>We've had <%= link_to @transporter.name, @transporter  %></b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <% end  %>
        <b> (from <%= link_to @request_delivery.user.name, @request_delivery.user %>) and deliverying it to</b><b style="color:#f35044"> Point B</b>
        <b> (to </b><b style="color:#f2ff5e">You</b><b>).</b><br>
      </div>
    </div>
    <% if @request_delivery.delivery_type == "myself" %>
        <div class="ready_to_go_wrapper" style="margin-bottom: 20px;">
          <%=  link_to "Go get more stuff", giveaways_path, class: "go_get_other" %>
        </div>
    <% elsif @request_delivery.delivery_type == "senddme" %>
        <div class="review_transporter_wrapper" style="margin-bottom: 20px;">
          <%=  link_to "Review Transporter", review_path(@request_delivery.id), class:"review_transporter modal-link trigger",
                       "data-target" => "#myModal",
                       "data-toggle" => "modal",
                       "data-backdrop" => "static" %>
        </div>
    <% end  %>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Item received
        <div class="giveaway_status_data">
          <% if @request_delivery.delivery_type == "myself" %>
              You've successfully picked up <b style="color:#f2ff5e"><%= @request_delivery.what %></b> from <b><%= link_to @request_delivery.user.name, @request_delivery.user %></b>!
          <% elsif @request_delivery.delivery_type == "senddme" %>
              We've had <b><%= link_to @transporter.name, @transporter  %></b> picking up <b style="color:#f2ff5e"><%= @request_delivery.what %></b> from <b><%= link_to @request_delivery.user.name, @request_delivery.user %></b>
              to <b style="color:#f2ff5e">You</b>.<br>
              The PayPal transaction has been successful.<br>
              Please take a few seconds to review <b><%= link_to @transporter.name, @transporter  %></b>.
          <% end  %>
        </div>
      </div>
    </div>
<% elsif @request_delivery.status == "TransporterReviewed" %>
    <div class="the_transporter">
      <div class="the_transporter_inner"  style="background-image: url('../assets/transporting_small.png');text-align:left">
        <div class="inner_title" style="padding-left: 55px;" >
          <b>Transporting</b>
        </div>
        <% if @request_delivery.delivery_type == "myself" %>
            <b>We've had </b><b style="color:#f2ff5e">You</b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <% elsif @request_delivery.delivery_type == "senddme" %>
            <b>We've had <%= link_to @transporter.name, @transporter  %></b><b> picking up this item from </b><b style="color:#6fba33"> Point A</b>
        <% end  %>
        <b> (from <%= link_to @request_delivery.user.name, @request_delivery.user %>) and deliverying it to</b><b style="color:#f35044"> Point B</b>
        <b> (to </b><b style="color:#f2ff5e">You</b><b>).</b><br>
      </div>
    </div>
    <div class="ready_to_go_wrapper" style="margin-bottom: 20px;">
      <%=  link_to "Go get more stuff", giveaways_path, class: "go_get_other" %>
    </div>
    <div class="giveaway_status_wrapper">
      <div class="giveaway_status_title">
        Transporter Reviewed
        <div class="giveaway_status_data">
          Thank you for reviewing <b><%= link_to @transporter.name, @transporter  %></b>!<br>
          Go ahead, get other stuff!
        </div>
      </div>
    </div>
<% end  %>

app/views/request_deliveries/renders/_from_for_everyone.html.erb
<div class="the_from_and_to_inner" style="background-image: url('../assets/LocationA_small.png');">
  <div class="inner_title">
    <b>From</b>
  </div>
  <%= @request_delivery.from %>
</div>

app/views/request_deliveries/renders/_upper_right_bar.html.erb
<% if @taking_user == current_user %>
    <% if @request_delivery.status == "Taken" && @my_taken_giveaway.present?  %>
        <b><%= link_to "I don't want it!", take_request_delivery_path(@request_delivery, type: "cancel"), method: :put, class: "challenge_accepted",
                       style: "background-color: #d67a31; background-image: url('../assets/challenge_cancelled.png');" %></b>
    <% end %>
<% elsif @request_delivery.user == current_user  %>
    <% if @request_delivery.status == "Taken" %>
        <b><%= link_to "Give it to someone else", another_path(@request_delivery), class: "challenge_accepted",
                       style: "background-color: #d67a31; font-size: 26px;background-image: url('../assets/challenge_cancelled.png');" %></b>
    <% end %>
<% else %>
    <% if @request_delivery.status == "Pending Confirmation" && @accepted_request.present?  %>
        <b><%= link_to "I won't pick it up!", accept_request_delivery_path(@request_delivery, type: "cancel"), method: :put, class: "challenge_accepted",
                       style: "background-color: #d67a31; font-size: 35px; background-image: url('../assets/challenge_cancelled.png');" %></b>
    <% elsif @request_delivery.status == "WaitingForTransporter" || @request_delivery.status == "Pending Confirmation" %>
        <% if current_user.nil? %>
            <% store_location %>
            <% session[:pick_up_after_not_signed_in_request_delivery_id] = @request_delivery.id %>
            <b><%=  link_to "I'll pick it up!", signup_path, class:"challenge_accepted", remote:true %></b>
        <% else %>
            <b><%= link_to "I'll pick it up!", accept_request_delivery_path(@request_delivery, type: "accept"), method: :put, class: "challenge_accepted" %></b>
        <% end %>
    <% end %>
<% end  %>