config/routes.rb
TheCarryProject::Application.routes.draw do
  default_url_options host: Rails.application.config.domain
  resources :users
  resources :user_reviews
  resources :phones
  resources :sessions, only: [:new, :create, :destroy]
  resources :request_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    put :take, on: :member
    resources :comments
  end
  resources :suggest_deliveries, only: [:create, :show, :edit, :update, :destroy] do
    put :accept, on: :member
    resources :comments
  end
  resources :password_resets
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/privacy_policy',    to: 'static_pages#privacy_policy'
  match '/terms_of_use',    to: 'static_pages#terms_of_use'
  match '/faq',    to: 'static_pages#faq'

  match '/request', to:'request_deliveries#new'
  match '/giveaways', to:'request_deliveries#index_takers'
  match '/pickups', to:'request_deliveries#index_transporters'

  match '/get_the_item/:request_delivery_id', to:'request_deliveries#get_the_item', as: 'get_the_item'
  match '/got_the_item/:request_delivery_id', to:'request_deliveries#got_the_item', as: 'got_the_item'
  match '/another/:request_delivery_id', to:'request_deliveries#another_taker', as: 'another'
  match '/edit_request_cost/:request_delivery_id', to:'request_deliveries#edit_cost', as:'edit_request_cost'
  match '/edit_request_what/:request_delivery_id', to:'request_deliveries#edit_what', as:'edit_request_what'
  match '/edit_request_picture/:request_delivery_id', to:'request_deliveries#edit_picture', as:'edit_request_picture'
  match '/edit_request_from/:request_delivery_id', to:'request_deliveries#edit_from', as:'edit_request_from'
  match '/edit_request_delivery/:request_delivery_id', to:'request_deliveries#edit_delivery', as:'edit_request_delivery'
  match '/edit_request_to/:request_delivery_id', to:'request_deliveries#edit_to', as:'edit_request_to'
  match '/edit_request_size/:request_delivery_id', to:'request_deliveries#edit_size', as:'edit_request_size'
  match '/edit_request_due_date/:request_delivery_id', to:'request_deliveries#edit_due_date', as:'edit_request_due_date'
  match '/edit_sending_person/:request_delivery_id', to:'request_deliveries#edit_sending_person', as:'edit_sending_person'
  match '/edit_receiving_person/:request_delivery_id', to:'request_deliveries#edit_receiving_person', as:'edit_receiving_person'

  match '/pre_confirm_request/:accepted_request_id', to: 'request_deliveries#pre_confirm', as:'pre_confirm_request'
  match '/confirm_request', to:'request_deliveries#confirm'
  match '/pre_cancel_request/:accepted_request_id', to: 'request_deliveries#pre_cancel', as:'pre_cancel_request'
  match '/pre_complete_request/:accepted_request_id', to: 'request_deliveries#pre_complete', as:'pre_complete_request'
  match '/complete_request', to:'request_deliveries#complete'

  match '/suggest', to:'suggest_deliveries#new'
  match '/suggestions', to:'suggest_deliveries#index'

  match '/edit_suggest_cost/:suggest_delivery_id', to:'suggest_deliveries#edit_cost', as:'edit_suggest_cost'
  match '/edit_suggest_from/:suggest_delivery_id', to:'suggest_deliveries#edit_from', as:'edit_suggest_from'
  match '/edit_suggest_to/:suggest_delivery_id', to:'suggest_deliveries#edit_to', as:'edit_suggest_to'
  match '/edit_suggest_due_date/:suggest_delivery_id', to:'suggest_deliveries#edit_due_date', as:'edit_suggest_due_date'
  match '/edit_freq/:suggest_delivery_id', to:'suggest_deliveries#edit_freq', as:'edit_freq'

  match '/pre_authorize_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_authorize', as:'pre_authorize_suggest'
  match '/confirm_suggestion', to:'suggest_deliveries#confirm'
  match '/authorize_suggestion', to:'suggest_deliveries#authorize'
  match '/pre_cancel_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_cancel', as:'pre_cancel_suggest'
  match '/pre_complete_suggest/:accepted_suggest_id', to: 'suggest_deliveries#pre_complete', as:'pre_complete_suggest'
  match '/complete_suggestion', to:'suggest_deliveries#complete'

  match '/activity', to:'activities#index'

  match '/verify/:id', to: 'users#verify', as:'verify'
  match '/confirm/:token', to: 'confirmations#confirm', as: 'confirm'

  match '/phone', to: 'phones#new'
  match '/send_code/:user_id', to: 'phones#send_code', as: 'send_code'
  match '/pre_verify_request/:request_delivery_id/:coming_from', to: 'phones#pre_verify_request', as: 'pre_verify_request'
  match '/pre_verify_suggest/:suggest_delivery_id/:coming_from', to: 'phones#pre_verify_suggest', as: 'pre_verify_suggest'
  match '/phone_verify/:user_id', to: 'phones#verify', as:'phone_verify'
  match '/phone_check', to: 'phone_verifications#phone_check'

  match '/reset_password', to: 'password_resets#new'
  match '/admin_reset/:user_id', to: 'password_resets#admin_reset', as:'admin_reset'

  match "empty_trash" => "users#empty_trash"

  match '/review/:request_delivery_id', to: 'user_reviews#new', as:'review'

  match '/auth/new' => 'authentications#new'
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => "authentications#failure" #OMNIAUTH
  match "facebook/logout", :to => "authentications#logout", :as => :logout_authentication

  get 'payments', to: 'payments#home', as: :home
  get 'payments/checkout', to: 'payments#checkout', as: :checkout
  get 'payments/cancel', to: 'payments#cancel', as: :cancel
  get 'payments/execute', to: 'payments#execute', as: :execute
  get 'payments/fail', to: 'payments#fail', as: :fail
  post 'payments/ipn_notification', to: 'payments#ipn_notification', as: :ipn_notification
  match '/details/:accepted_task_id/:req_or_sugg', to: 'payments#details', as: 'details'

end

app/controllers/suggest_deliveries_controller.rb
class SuggestDeliveriesController < ApplicationController
  before_filter :signed_in_user, :except => [:show, :index, :new, :create]
  before_filter :correct_user,   only: [:destroy, :update]
  respond_to :html, :js

  def show
    @suggest_delivery = SuggestDelivery.find(params[:id])
    if !current_user.nil?
      @accepted_suggest = AcceptedSuggest.find_by_user_id_and_suggest_delivery_id(current_user.id,@suggest_delivery.id)
      @my_phone = Phone.find_by_user_id(current_user.id)
    end
    @facebook_authentication = Authentication.find_by_user_id(@suggest_delivery.user.id)
    @phone = Phone.find_by_user_id(@suggest_delivery.user.id)
    @commentable = @suggest_delivery
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    if current_user.nil?
      @suggest_delivery = SuggestDelivery.new
    else
      @suggest_delivery = current_user.suggest_deliveries.build
    end
  end

  def create
    if current_user.nil?
      @suggest_delivery = SuggestDelivery.new(params[:suggest_delivery])
      if @suggest_delivery.valid?
        session[:suggest_delivery_size] = @suggest_delivery.size
        session[:suggest_delivery_from] = @suggest_delivery.from
        session[:suggest_delivery_to] = @suggest_delivery.to
        session[:suggest_delivery_cost] = @suggest_delivery.cost
        session[:suggest_delivery_currency] = @suggest_delivery.currency
      end
    else
      @suggest_delivery = current_user.suggest_deliveries.build(params[:suggest_delivery])
      if @suggest_delivery.save
        flash[:success] = "Thank you!<br>
                                              <div class='sub_flash_text'>Your delivery suggestion was successfully added to our lists. <br>
                                              There are some more details to add though.<br>
                                              <b style=\"color:#ff9054\">Add</b> <img src=\"../assets/missing_detail.png\"> all details and get priority in our lists!</div>".html_safe
        respond_with(@suggest_delivery) do |format|
          format.html { redirect_to suggest_delivery_url(@suggest_delivery)}
        end
      end
    end
  end

  def index
    @search = SuggestDelivery.search(params[:search])
    @suggest_feed_items = @search.all.sort_by { |a| a.has_all_details ? 0 : 1}
  end

  def edit_cost
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    if @suggest_delivery.user == current_user
      render "edit_cost.html.erb", :layout => false
    end
  end

  def edit_from
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    if @suggest_delivery.user == current_user
      render "edit_from.html.erb", :layout => "empty"
    end
  end

  def edit_to
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    if @suggest_delivery.user == current_user
      render "edit_to.html.erb", :layout => "empty"
    end
  end

  def edit_due_date
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    if @suggest_delivery.user == current_user
      render "edit_due_date.html.erb", :layout => "empty"
    end
  end

  def edit_freq
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    if @suggest_delivery.user == current_user
      render "edit_freq.html.erb", :layout => false
    end
  end

  def update
    @suggest_delivery = SuggestDelivery.find(params[:id])
    if @suggest_delivery.status != "Open"
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot edit the details of your suggestion since someone has already accepted it.</div>".html_safe
      redirect_to :back
    else
      if @suggest_delivery.update_attributes( params[:suggest_delivery])
        @suggest_delivery.check_all_details
        flash[:success] = "Thank you!<br><div class='sub_flash_text'>Your details were successfully updated.</div>".html_safe
        respond_with(@suggest_delivery) do |format|
          format.html { redirect_to suggest_delivery_url(@suggest_delivery)}
        end
      end
    end
  end

  def destroy
    @suggest_delivery = SuggestDelivery.find(params[:id])
    if @suggest_delivery.status != "Open"
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot delete your delivery suggestion since someone has already accepted it.</div>".html_safe
      redirect_to :back
    else
      @suggest_delivery.destroy
      flash[:success] = "Thank you!<br><div class='sub_flash_text'>Your delivery suggestion has been successfully deleted.</div>".html_safe
      redirect_to suggestions_path
    end
  end

  def accept
    @suggest_delivery = SuggestDelivery.find(params[:id])
    type = params[:type]
    if current_user != @suggest_delivery.user
      if type == "accept"
        current_user.suggest_accepts << @suggest_delivery
        @suggest_delivery.accept_suggest
        redirect_to :back
        flash[:success] = "Thank you!<br>
                                              <div class='sub_flash_text'>You've chosen to accept <b>#{@suggest_delivery.size} sized items</b> delivery suggestion.<br>
                                              <b>#{@suggest_delivery.user.name}</b>, the creator of the suggestion, will be notified. <br>
                                              Now <b>#{@suggest_delivery.user.name}</b> must confirm you.</div>".html_safe
        @accepted_suggest = AcceptedSuggest.find_by_suggest_delivery_id(@suggest_delivery.id)
        @creating_user = User.find_by_id(@suggest_delivery.user_id)
        @accepting_user = User.find_by_id(@accepted_suggest.user_id)
        NotifMailer.new_accepted_suggest(@creating_user,@accepting_user,@suggest_delivery).deliver
      elsif type == "cancel"
        if @suggest_delivery.status == "Open"
          flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot cancel an Open request.</div>".html_safe
          redirect_to :back
        elsif @suggest_delivery.status == "Confirmed"
          flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot cancel a Confirmed suggestion.</div>".html_safe
          redirect_to :back
        elsif @suggest_delivery.status == "Complete"
          flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot cancel a Complete suggestion.</div>".html_safe
          redirect_to :back
        else
          current_user.suggest_accepts.delete(@suggest_delivery)
          redirect_to :back
          @suggest_delivery.cancel_suggest
          flash[:success] = "Thank you!<br><div class='sub_flash_text'>You've chosen to cancel your acceptance of the suggestion.</div>".html_safe
        end
      else
        redirect_to :back
      end
    else
      redirect_to :back
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>You cannot accept your own delivery suggestions.</div>".html_safe
    end
  end

  def confirm
    @phone = Phone.find_by_user_id(current_user.id)
    @accepted_suggest = AcceptedSuggest.find(params[:accepted_suggest_id])
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    @suggest_creator = User.find(@suggest_delivery.user_id)
    @confirmed_user = User.find( @accepted_suggest.user_id)
    if @suggest_creator == current_user  && @phone.present? && @phone.verified
      if @accepted_suggest.save
        @accepted_suggest.confirm_accepted_suggest
        @suggest_delivery.confirm_suggest
        flash[:success] = "Great!<br><div class='sub_flash_text'>You've chosen to confirm <b>#{@confirmed_user.name}</b>
                                            For your suggestion<b> #{@suggest_delivery.size} sized items</b></div>".html_safe
        if Rails.env.production?
          NotifMailer.new_confirmed_suggest(@suggest_creator,@confirmed_user,@suggest_delivery).deliver
        end
      end
    end
    redirect_to activity_path
  end

  def pre_authorize
    @accepted_suggest = AcceptedSuggest.find_by_id(params[:accepted_suggest_id])
    @suggest_delivery = SuggestDelivery.find_by_id(@accepted_suggest.suggest_delivery_id)
    render "pre_authorize.html.erb", :layout => false
  end

  def pre_cancel
    @accepted_suggest = AcceptedSuggest.find_by_id(params[:accepted_suggest_id])
    render "pre_cancel.html.erb", :layout => false
  end

  def pre_complete
    @accepted_suggest = AcceptedSuggest.find_by_id(params[:accepted_suggest_id])
    @suggest_delivery = SuggestDelivery.find_by_id(@accepted_suggest.suggest_delivery_id)
    render "pre_complete.html.erb", :layout => false
  end

  def authorize
    @accepted_suggest = AcceptedSuggest.find(params[:accepted_suggest_id])
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    @suggest_creator = User.find(@suggest_delivery.user_id)
    @confirmed_user = User.find( @accepted_suggest.user_id)
    if @confirmed_user == current_user
      redirect_to :controller => 'payments',
                  :action => 'checkout',
                  :req_or_sugg => "suggest_delivery",
                  :task_creator_id => @suggest_creator.id,
                  :confirmed_user_id => @confirmed_user.id,
                  :task_id => @suggest_delivery.id,
                  :accepted_task_id => @accepted_suggest.id
    else
      flash[:failure] = "Sorry!<br><div class='sub_flash_text'>Only the creator of the suggestion can confirm it.</div>".html_safe
    end
  end

  def complete
    @accepted_suggest = AcceptedSuggest.find(params[:accepted_suggest_id])
    @suggest_delivery = SuggestDelivery.find(params[:suggest_delivery_id])
    @suggest_creator = User.find(@suggest_delivery.user_id)
    @suggest_payment = SuggestPayment.find_by_suggest_delivery_id(@suggest_delivery.id)
    @confirmed_user = User.find( @accepted_suggest.user_id)

app/views/suggest_deliveries/create.js.erb
var form = $('#new_suggest_delivery');

// Delete errors from previous submission
if ($(".request_suggest_delivery_errors")[0]){
    $('.request_suggest_delivery_errors').remove();
}

<% if @suggest_delivery.errors.any? %>

// Create a list of errors
var errors = $('<ul />');

// Display only first error for each field
<% @suggest_delivery.errors.each do |attribute, message| %>
    <% if @suggest_delivery.errors[attribute].first == message %>
        errors.append('<li><%= escape_javascript(message) %></li>');
    <% end %>
<% end %>

// Display errors before the form
$('<div />').addClass('request_suggest_delivery_errors').html(errors).appendTo("#new_suggest_delivery").hide().fadeIn('slow');

<% else %>
    <% if current_user.nil? %>
        <% store_location %>
        window.location.href = "<%=signin_path %>"
    <% else %>
        // On successful creation of new user, redirect to main page
        window.location.href = "<%=suggest_delivery_url(@suggest_delivery) %>"
    <% end %>

<% end %>

app/views/suggest_deliveries/edit_cost.html.erb
<div class="edit_delivery_field_wrapper" style="background-image: url('../assets/money.png');">
  <%= form_for(@suggest_delivery, :remote => true ) do |f| %>
      <div class="edit_delivery_field_cost" style="font-size: 30px;">
            How much will you charge?<%= f.text_field :cost  %><%= f.select :currency, options_for_select(%w[ILS USD EUR], :selected => @suggest_delivery.currency) %>
      </div>
      <div class="edit_update">
        <%= f.submit "Update Request" , :id => 'submit_delivery' %>
      </div>
  <% end  %>
</div>

app/views/suggest_deliveries/edit_due_date.html.erb
<div class="edit_delivery_field_wrapper" style="background-image: url('../assets/Calendar.png');">
  <%= form_for(@suggest_delivery, :remote => true ) do |f| %>
      <div class="edit_delivery_field_due_date">
        <% if @suggest_delivery.when.blank? %>
            When? <%= f.text_field :when, :placeholder => "mm/dd/yyyy", :class => "datepicker" %>
        <% else  %>
            When? <%= f.text_field :when, :placeholder => "mm/dd/yyyy", :class => "datepicker", :value => "#{@suggest_delivery.when.strftime("%d/%m/%Y")}" %>
        <% end  %>
      </div>
      <div class="edit_update">
        <%=  f.submit "Update Suggestion" , :id => 'submit_delivery'%>
      </div>
  <% end  %>
</div>

app/views/suggest_deliveries/edit_freq.html.erb
<div class="edit_delivery_field_wrapper" style="background-image: url('../assets/Freq.png');">
  <%= form_for(@suggest_delivery, :remote => true ) do |f| %>
      <div class="edit_delivery_field_freq">
        <%= f.label :frequency, "Frequency?" %>
        <%= f.hidden_field :frequency %>
        <div class="new_freq" style="width:400px;">
          <% if @suggest_delivery.frequency.present? && @suggest_delivery.frequency == "Single" %>
              <div class="freq_box" id="single" style="background-color: #d05e0b; background-image: url('../assets/freq_once.png');"
               onclick="style.backgroundColor='#d05e0b';
                       document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                       document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Single';">
            Single
          </div>
          <% else  %>
              <div class="freq_box" id="single" style="background-image: url('../assets/freq_once.png');"
                   onclick="style.backgroundColor='#d05e0b';
                           document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                           document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Single';">
                Single
              </div>
          <% end  %>
          <% if @suggest_delivery.frequency.present? && @suggest_delivery.frequency == "Daily" %>
          <div class="freq_box" id="daily" style="background-color: #d05e0b; background-image: url('../assets/freq_daily.png'); margin-left:10px;"
               onclick="style.backgroundColor='#d05e0b';
                       document.getElementById('single').style.backgroundColor = '#bcbcbc';
                       document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Daily';">
            Daily
          </div>
          <% else  %>
              <div class="freq_box" id="daily" style="background-image: url('../assets/freq_daily.png'); margin-left:10px;"
                   onclick="style.backgroundColor='#d05e0b';
                           document.getElementById('single').style.backgroundColor = '#bcbcbc';
                           document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Daily';">
                Daily
              </div>
          <% end  %>
         <% if @suggest_delivery.frequency.present? && @suggest_delivery.frequency == "Weekly" %>
          <div class="freq_box" id="weekly" style="background-color: #d05e0b; background-image: url('../assets/freq_weekly.png'); margin-left:10px;"
               onclick="style.backgroundColor='#d05e0b';
                       document.getElementById('single').style.backgroundColor = '#bcbcbc';
                       document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                       document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Weekly';">
            Weekly
          </div>
          <% else  %>
              <div class="freq_box" id="weekly" style="background-image: url('../assets/freq_weekly.png'); margin-left:10px;"
                   onclick="style.backgroundColor='#d05e0b';
                           document.getElementById('single').style.backgroundColor = '#bcbcbc';
                           document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                           document.getElementById('monthly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Weekly';">
                Weekly
              </div>
          <% end  %>
           <% if @suggest_delivery.frequency.present? && @suggest_delivery.frequency == "Monthly" %>
          <div class="freq_box" id="monthly" style="background-color: #d05e0b; background-image: url('../assets/freq_monthly.png'); margin-left:10px;"
               onclick="style.backgroundColor='#d05e0b';
                       document.getElementById('single').style.backgroundColor = '#bcbcbc';
                       document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                       document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                       document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Monthly';">
            Monthly
          </div>
          <% else  %>
              <div class="freq_box" id="monthly" style="background-image: url('../assets/freq_monthly.png'); margin-left:10px;"
                   onclick="style.backgroundColor='#d05e0b';
                           document.getElementById('single').style.backgroundColor = '#bcbcbc';
                           document.getElementById('daily').style.backgroundColor = '#bcbcbc';
                           document.getElementById('weekly').style.backgroundColor = '#bcbcbc';
                           document.getElementById('edit_suggest_delivery_'+<%= @suggest_delivery.id %>).suggest_delivery_frequency.value = 'Monthly';">
                Monthly
              </div>
          <% end  %>
        </div>
      </div>
      <div class="edit_update">
        <%=  f.submit "Update Request" , :id => 'submit_delivery'%>
      </div>
  <% end  %>
</div>

app/views/suggest_deliveries/edit_from.html.erb
<div class="edit_delivery_field_wrapper" style="background-image: url('../assets/LocationA.png');">
  <%= form_for(@suggest_delivery, :remote => true, :html => { :id => "edit_from" }) do |f| %>
      <div class="edit_delivery_field_from">
        <%= f.label :from, "From?" %><%= f.text_field :from, :value => @suggest_delivery.from, :class => "address_field" %>
      </div>
      <div class="edit_update">
        <%= f.submit "Update Suggestion" , :id => 'submit_delivery' %>
      </div>
  <% end  %>
</div>

app/views/suggest_deliveries/edit_to.html.erb
<div class="edit_delivery_field_wrapper" style="background-image: url('../assets/LocationB.png');">
  <%= form_for(@suggest_delivery, :remote => true, :html => { :id => "edit_to" }) do |f| %>
      <div class="edit_delivery_field_to">
        <%= f.label :to, "To?" %><%= f.text_field :to, :value => @suggest_delivery.to, :class => "address_field" %>
      </div>
      <div class="edit_update">
        <%= f.submit "Update Suggestion" , :id => 'submit_delivery' %>
      </div>
  <% end  %>
</div>

app/views/suggest_deliveries/index.html.erb
<%=  render 'shared/suggest_feed' %>

app/views/suggest_deliveries/pre_authorize.html.erb
<div class="modal_title">
  Payment Authorization
</div>
<div class="modal_text">
  You're about to be redirected to <div class="special">PayPal</div> in order to authorize future payment.<br><br>
  By proceeding you are aware that <div class="special">sendd.me</div> takes 15% commission from the amount being authorized (<div class="special"><%= @suggest_delivery.cost %> <%= @suggest_delivery.currency %></div>).
</div>
<div class="modal_proceed">
  <%=  link_to "Proceed to PayPal",
               {:controller => "suggest_deliveries",
                :action => "authorize",
                :accepted_suggest_id => @accepted_suggest.id,
                :suggest_delivery_id => @accepted_suggest.suggest_delivery_id  }, :id => "submit_activity",
               class: "trigger" %>
</div>



app/views/suggest_deliveries/pre_cancel.html.erb
<div class="modal_title">
  Cancel Payment Preapproval
</div>
<div class="modal_text">
  You're about to be cancel a Preapproved Payment Authorization you've made to <div class="special">PayPal</div>.<br><br>
  The above cancellation can be issued as late as 3 days prior to completion of the delivery suggestion.
</div>
<div class="modal_proceed">
<%=  link_to "Cancel Payment",
               {:controller => "payments",
                :action => "cancel",
                :req_or_sugg => "suggest_delivery",
                :accepted_task_id => @accepted_suggest.id,
                :task_id => @accepted_suggest.suggest_delivery_id  }, :id => "submit_activity",
               class: "trigger" %>
</div>



app/views/suggest_deliveries/pre_complete.html.erb
<div class="modal_title">
  Delivery Task Completion
</div>
<div class="modal_text">
  You're about to be mark your delivery suggestion as complete.<br>
  This will trigger  a transaction from <div class="special">PayPal</div> for <div class="special"><%= @suggest_delivery.cost %> <%= @suggest_delivery.currency %></div>.<br><br>
  <div class="special">You</div> will receive 85% of the above amount.<br>
  <div class="special">sendd.me</div> will receive 15% of the above amount.<br><br>
  By proceeding you admit to having performed the delivery task.
</div>
<div class="modal_proceed">
<%=  link_to "Complete Delivery",
               {:controller => "suggest_deliveries",
                :action => "complete",
                :accepted_suggest_id => @accepted_suggest.id,
                :suggest_delivery_id => @accepted_suggest.suggest_delivery_id  }, :id => "submit_activity",
               class: "trigger" %>
</div>